#!/bin/bash -ue

LLVM_SDK_ROOT=/opt/llvm

. $LLVM_SDK_ROOT/common.sh

if [ -z ${OPTIM_SIZE+x} ]; then 

CFLAGS="-Ofast"
LDFLAGS=""

else

CFLAGS="-Oz"
LDFLAGS="-Wl,-s"

fi

CFLAGS="$CFLAGS \
-fno-fast-math \
-fomit-frame-pointer \
-fno-stack-protector"

LDFLAGS="$LDFLAGS"

run_exe
