#!/bin/sh -ue

LLVM_SDK_ROOT=/opt/llvm

. $LLVM_SDK_ROOT/common.sh

CFLAGS="\
-Ofast \
-flto=thin \
-fno-fast-math \
-fomit-frame-pointer \
-gline-tables-only \
-mllvm -polly -mllvm -polly-parallel -lgomp -mllvm -polly-vectorizer=stripmine \
-fno-stack-protector"

LDFLAGS=""

run_exe

